### ISSUE TITLE
Time component of now() calculation not available

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#226] opened 2017-11-17 21:31 UTC
[now-time.xml.txt](https://github.com/opendatakit/javarosa/files/1483901/now-time.xml.txt)

When an XLSForm is converted using pyxform, all calculates are of type `string`. @mdudzinski describes [here](https://github.com/opendatakit/javarosa/issues/199#issuecomment-345254947) why this leads to the time component not showing up. This is the `now3` case in the form above. Perhaps we should have a special case for a type of string that uses datetime to guarantee no info is lost.

<strike>`format-date(now(), "%Y-%m-%e %H:%M:%S.%3")` doesn't show time either. I don't think this is related and don't have a good explanation. This is the `now1` case in the form above.</strike> addressed in #261

**Comment by mdudzinski** [comment] 2017-11-24 14:12
@lognaturel You need to use `format-date-time` function to get the time component. 

The easiest solution to solve this is to make `DateTimeData` to be the default value if a calculation result is instance of `Date` and its `dataType` (the type set in the binding) isn't date, date time or time. 
So this:
```
if ( dataType == Constants.DATATYPE_DATE_TIME) {
  return new DateTimeData((Date)val);
}
else if ( dataType == Constants.DATATYPE_TIME ) {
  return new TimeData((Date)val);
} else {
  return new DateData((Date)val);
}
```
should be changed to: 
```
if ( dataType == Constants.DATATYPE_DATE) {
  return new DateData((Date)val);
}
else if ( dataType == Constants.DATATYPE_TIME ) {
  return new TimeData((Date)val);
} else {
  return new DateTimeData((Date)val);
}
```

**Comment by mdudzinski** [comment] 2017-11-24 14:20
@lognaturel Btw, isn't this a duplicate of #144 😃 ?

**Comment by lognaturel** [comment] 2017-11-27 23:45
😖 I was pretty sure I had seen this issue before but for some reason I couldn't find it!! I think I only looked on the forum and in Collect.

I think changing the default case as you've suggested would be fine. It might change behavior that someone is depending on but it's to add more info not to further constrain what's displayed so I think it's ok.

I was looking at https://opendatakit.github.io/xforms-spec/#fn:format-date which suggests `format-date` should also be able to format time. I've confirmed that `format-date-time` does work as expected. I think the JavaRosa implementation should be updated; this conversation can continue at opendatakit/xforms-spec#20.

**Comment by lognaturel** [comment] 2018-03-05 05:29
The issue with `calculates` (`now3` in the sample form) still needs to be addressed.

**Comment by ggalmazor** [comment] 2018-03-06 09:31
I'd want to work on this one but I'm failing to write a test that would let me check my work. I'm using the following simplified form:

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>data</h:title>
    <model>
      <instance>
        <data id="data">
          <now/>
          <now_note/>
          <meta>
            <instanceID/>
          </meta>
        </data>
      </instance>
      <!-- time component not populated because value type is string -->
      <bind calculate="now()" nodeset="/data/now" type="string"/>
      <bind nodeset="/data/now_note" readonly="true()" type="string"/>

      <bind calculate="concat('uuid:', uuid())" nodeset="/data/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/data/now_note">
      <label><output value="/data/now"/></label>
    </input>
  </h:body>
</h:html>
```

I'm doing this to parse this form on a test:

```java
FormParseInit fpi = new FormParseInit();
new FormParseInit().setFormToParse(r("calculate-now.xml").toString());
formDef = fpi.getFormDef();
ctrl = fpi.getFormEntryController();
model = fpi.getFormEntryModel();
```

In my test, I'm doing this:

```java
FormIndex now = new FormIndex(0, 0, formDef.getMainInstance().getRoot().getChild("now_note", 0).getRef());
FormEntryPrompt formEntryPrompt = new FormEntryPrompt(formDef, now);
String questionText = formEntryPrompt.getQuestionText();
```

I'd expect `questionText` to have some content derived from the `now` field on the instance, but I'm getting an empty string... 

Any ideas?

**Comment by lognaturel** [comment] 2018-03-12 22:13
I don't think the `calculate` ever gets evaluated with your way of loading the form. I've verified that with something like this:
```
 final FormDef formDef = parse(r("calculate-now.xml")).formDef;
formDef.initialize(true, new InstanceInitializationFactory());
```
your test code then does show just the date part of `now()`. 

@dcbriccetti do you have a simpler strategy?

**Comment by ggalmazor** [comment] 2018-03-13 17:51
Thanks for the tip @lognaturel. That got me on track again :)

It's true that we still need to change the implementation of `Recalculate.wrapData(Object val, int dataType)` for `val` values that are instances of `Date` as @mdudzinski is suggesting but even if we change the type of that model to `dateTime`, using that model in an `<output>` will get only the date part out.

This is because `XPathFuncExpr.toString(Object o)` is called while eval-ing the label contents. The current implementation of `XPathFuncExpr.toString(Object o)` for `Date` objects is:

```java
DateUtils.formatDate((Date)o, DateUtils.FORMAT_ISO8601)
```

Which only outputs the date part of the object.  We could use `DateUtils.formatDateTime()` but this would affect all `Date` instances that reach this method whether they come from a `DateTimeData` or from a `DateData` (we can't know).

Because of this, I'm going to test for this with the following form, which avoid the `toString()` problem by calculating a formatted date-time that outputs the time part:

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>data</h:title>
    <model>
      <instance>
        <data id="data">
          <now/>
          <now_format/>
          <now_note/>
          <meta>
            <instanceID/>
          </meta>
        </data>
      </instance>
      <!-- time component not populated because value type is string -->
      <bind calculate="date('2018-01-01T10:20:30.400')" nodeset="/data/now" type="string"/>
      <bind calculate="format-date-time(/data/now, '%Y-%m-%dT%H:%M:%S.%3')" nodeset="/data/now_format" type="string"/>
      <bind nodeset="/data/now_note" readonly="true()" type="string"/>

      <bind calculate="concat('uuid:', uuid())" nodeset="/data/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/data/now_note">
      <label><output value="/data/now_format"/></label>
    </input>
  </h:body>
</h:html>
```

**Closed** 2018-03-13 23:18 UTC
Labels: contributor friendly, quick win
