### ISSUE TITLE
If statements with incorrect number of parameters

### ISSUE THREAD

**Issue by joeflack4** [opendatakit/javarosa#480] opened 2019-08-22 17:54 UTC
#### Problem description
An issue in which `if()` statement is used without the correct number of parameters (e.g. 4+ params).

#### Steps to reproduce the problem
1. Create an XLSForm and use an erroneous if statement with too many parameters, e.g. an arbitrary example: `if(1=0, 1, 0, 1)`. Or use the attached form.
2. Try to run ODK Validate on this form. The issue isn't caught.

#### Expected behavior
The error is caught and an error message is presented.

#### Attachments
[FQCSBaseline-V22-20190814-jef.xlsx](https://github.com/opendatakit/validate/files/3531342/FQCSBaseline-V22-20190814-jef.xlsx)

**Comment by lognaturel** [comment] 2019-09-06 18:18
Thanks, @joeflack4! JavaRosa does the parameter count checking so that's why I moved the issue here. I think this might be a little more complex than what you've described, though.

I just took a quick look and the `if` function definition does verify that there are exactly three arguments. Did you actually try a form with the arbitrary example you list and could you attach it?

I haven't looked at your form in great detail but I see that there a lot of `if`s. Is it possible that the one with the problem is on a node that's not relevant before data is entered?

**Comment by joeflack4** [comment] 2019-09-06 18:51
Oh, cool. I didn't know you could move issues to a different repo o.O

Hmm, sorry Hélène. I couldn't replicate. And I don't even remember why I included the whole form, rather than just an example, since this is pretty much a one-liner. In any event, from what I remember, such an `if()` statement with more than 3 parameters was able to be converted (somehow)... Perhaps it was nested or who knows. If I find it again I'll show it to you. From what I remember, we experienced a runtime error in Collect.

So until I come across this again, I think we should close this issue.

---

Also, what about the following issue I posted in ODK Validate; it seems to be similar to this one as well: https://github.com/opendatakit/validate/issues/60

**Comment by priusak** [comment] 2019-09-06 19:11
Dňa pi 6. 9. 2019, 20:51 Joe Flack <notifications@github.com> napísal(a):

**Comment by lognaturel** [comment] 2019-09-06 19:21
> I didn't know you could move issues to a different repo

It's a [new-ish feature](https://help.github.com/en/articles/transferring-an-issue-to-another-repository)! 🚀 

> I couldn't replicate.

That's good news! I tried to replicate what I described with relevance and couldn't get a badly-formed if through. Definitely do re-open if you can provide the if statement that fails and the exact runtime error you get.

**Closed by lognaturel** 2019-09-06 19:21 UTC

**Comment by joeflack4** [comment] 2019-09-06 19:28
@lognaturel Oh cool. Uhh, is @priusak a new feature too, haha? Looks like a bot.
